# Form implementation generated from reading ui file 'c:\PROJECTS\SKLAD\mouserResultPrompt.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 92)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spin_nr_of_results = QtWidgets.QSpinBox(Form)
        self.spin_nr_of_results.setMinimum(1)
        self.spin_nr_of_results.setMaximum(50)
        self.spin_nr_of_results.setObjectName("spin_nr_of_results")
        self.gridLayout.addWidget(self.spin_nr_of_results, 1, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pb_load = QtWidgets.QPushButton(Form)
        self.pb_load.setObjectName("pb_load")
        self.gridLayout.addWidget(self.pb_load, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pb_cancel = QtWidgets.QPushButton(Form)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 2, 3, 1, 1)
        self.la_vysledky = QtWidgets.QLabel(Form)
        self.la_vysledky.setObjectName("la_vysledky")
        self.gridLayout.addWidget(self.la_vysledky, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "kolik jich chceš nahrát ? (max 50)"))
        self.pb_load.setText(_translate("Form", "Nahrát"))
        self.label.setText(_translate("Form", "Na mouser bylo nalezeno víc výsledků"))
        self.pb_cancel.setText(_translate("Form", "Zrušit"))
        self.la_vysledky.setText(_translate("Form", "..."))
